### ISSUE TITLE
Can't pass Neon from MetaMask to Phantom if missing SOL

### ISSUE THREAD

**Issue by s-medvedev** [neonevm/neon-support#7]
**Bug Description**
When I was tried Neon to Solana it asked me SOL for transaction fee It needs to ask NEON for transaction so all my tarnsactions Failed on metamusk

**Steps to Reproduce**
1. Go to https://neonpass.live
2. Try to pass NEON from MetaMask to Phantom (with empty SOL balance)

**Actual Behavior**
![mora](https://user-images.githubusercontent.com/103234844/162365442-32c10634-d476-44cb-896f-6996e0b2670b.png)

**Expected Behavior**
NEON passed successfully.

**Comment by WebKieth** [comment]
@s-medvedev okay, now I calculate withdraw action fee as web3 ethereum library getGasPrice.
It pass me a number in string and I use the base ERC20 decimal - 18 to create UI friendly price. But it is not a neon token. Usually I get the number like 0.000000470 but when i set the transaction to metamask window - it compute ~1.2 neon token fee.

**Comment by WebKieth** [comment]
@s-medvedev @gigimon @vakond 

This issue is related to https://github.com/neonlabsorg/neon-support/issues/5
It's unite in one current problem - we didn't implement logic of calculating fees for difficult cases. Current core logic describe four different cases:
1. Deposit Neon  
We use only solana network transaction - for fee just check sol balance - and it works properly  
2. Withdraw Neon  
We use only ethereum network - so we get gas price. It seems to small when we get it through web3 api, but in metamask we see different value. In my case ~1.4 neon  costs **each** transaction, not only first  
3. Deposit mint token
As first case - it works properly  
4. Withdraw mint token  
The most interesting case. Firstly we create approve instruction for ethereum network. Secondly we create transfer instruction for solana network. So this is the second main question.

Problems:  
1. Why gas price in second case costs too much each time? 
2. What should interface do with fee logic in fourh case? Do we grab fee from solana or ethereum? Or both?

**Comment by gigimon** [comment]
The problem was resolved and deployed
